### ISSUE TITLE
Implement Response

### ISSUE THREAD

**Issue by phuu** [phuu/fetch-engine#14]
`Request` should be dome first, as per #13.

Implement & test [Response](https://fetch.spec.whatwg.org/#response-class) from the fetch spec.

Probably a new file in `src` called `Response.ts` with a matching `Response.test.ts` file. It should implement the `Response` class from the `whatwg-fetch` typings:

```js
class Response implements Response {
   // ...
}
```

Please reuse the [Body](https://fetch.spec.whatwg.org/#body-mixin) mixin.

**Comment by ahume** [comment]
Response class was implemented in 199b75d.
