### ISSUE TITLE
Document that fetchEngine is a function, not a constructor

### ISSUE THREAD

**Issue by phuu** [phuu/fetch-engine#45]
The README is p out of date.

Specifically, `fetch-engine` is now called as a normal function, and passed a `FetchGroup`, or an object that can be passed to a `FetchGroup`:

```js
var fetch = fetchEngine(new FetchGroup({ ... }));
```

**Comment by jackfranklin** [comment]
I'll take this one, reckon I can just about manage!

**Comment by phuu** [comment]
My hero :heart:
