### ISSUE TITLE
Switch to tape

### ISSUE THREAD

**Issue by phuu** [phuu/fetch-engine#51]
I'm loathe to do it because ava is nice, but browsers. This unblocks #16.

**Comment by phuu** [comment]
If anybody wants to pick this up, I've done a partial conversation in f5a5e5c.

**Comment by ahume** [comment]
I'll do Headers.

**Comment by phuu** [comment]
We also need to be careful to wrap tests that return a Promise in something that will fail the test if the Promise rejects, as we could be missing failures that ava would have caught.

**Comment by ahume** [comment]
What would this look like?

**Comment by phuu** [comment]
I suppose:

```js
test('Blah blah', wrap(t => { ... }));
```

Promise.resolve the return value and catch errors?

**Comment by phuu** [comment]
This is now complete.
