### ISSUE TITLE
Comments in package.json

### ISSUE THREAD

**Issue by phuu** [phuu/fetch-engine#56]
The `karma` branch has comments in package.json — let's drop what's explained by reading the script and move the useful stuff into the README.

**Comment by thelambdaparty** [comment]
@phuu I'm finishing another project at the moment, but tomorrow i'll be available and help where possible. 

What's the best way to communicate to you about another project? (related to FlightJS)

**Comment by phuu** [comment]
Great stuff. [Email I guess!](mailto:tgvashworth@gmail.com)
